name: ecommerce_project
version: '1.0'
profile: ecommerce_project

model-paths: ["models"]
seed-paths: ["data"]

seeds:
  ecommerce_project:
    +schema: raw
    +quote_columns: false

models:
  ecommmerce_project:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table